name: "Validate Gradle Wrapper"
permissions:
  contents: read

on:
  workflow_dispatch

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v4
